version: "3"
services:
  telegraf:
    image: telegraf:1.3.4-alpine
    restart: "no"
    ports:
      - 8092:8092/udp
      - 8125:8125/udp
      - 8094:8094
    networks:
      - devnet
  scc-server:
    image: cgelias/spring-cloud
    container_name: scc-server
    stdin_open: true
    volumes:
      - /home/pnradmin/elias_test/scc-encrypted-config/src/configuration-service:/local/git
    networks:
      - devnet
  scc-client:
    image: cgelias/spring-cloud
    container_name: scc-client
    stdin_open: true
    volumes:
      - /home/pnradmin/elias_test/scc-encrypted-config/src/configuration-client:/local/git
    networks:
      - devnet
networks:
  devnet: