version: "3"
services:
  telegraf:
    image: telegraf:1.3.4-alpine
    restart: "no"
    ports:
      - 8092:8092/udp
      - 8125:8125/udp
      - 8094:8094
    networks:
      - devnet
  scc:
    image: cgelias/spring-cloud
    stdin_open: true
    networks:
      - devnet
networks:
  devnet: