version: "3"
services:
  telegraf:
    image: telegraf:1.3.4-alpine
    restart: "no"
    ports:
      - 8092:8092/udp
      - 8125:8125/udp
      - 8094:8094
    networks:
      - devnet
  maven:
    image: maven:3.5.2-jdk-7
    networks:
      - devnet